export * as GuestAPI from "./user/guest.api";
export * as AuthAPI from "./auth/auth.api";
export * as AdminAPI from "./user/admin.api";
export * as TraderAPI from "./user/trader.api";
export * as AffilitorAPI from "./user/affiliator.api";
export * as BankAPI from "./bank/bank.api";
export * as CryptoAPI from "./crypto/crypto.api";
export * as BrokerAPI from "./broker/broker.api";
export * as WithdrawalAPI from "./withdrawal/withdrawal.api";